language: node_js
node_js:
  - "10"
jobs:
  include:
    - stage: build
      script: grunt travis
cache:
  directories:
    - "node_modules"
notifications:
  email:
    recipients: 
    - helpfulscripts@gmail.com
    on_success: never # default: change
    on_failure: always # default: always